apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vllm-monitor
  namespace: monitoring
  labels:
    release: observability
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: vllm-server
  endpoints:
  - port: http-metrics
    path: /metrics
    interval: 10s
    scrapeTimeout: 9s
